with
    bureau as (
        select
            SK_ID_CURR
            , SK_ID_BUREAU
            , CREDIT_ACTIVE
            , CREDIT_CURRENCY
            , CAST(DAYS_CREDIT AS NUMERIC) AS DAYS_CREDIT
            , CAST(CREDIT_DAY_OVERDUE AS NUMERIC) AS CREDIT_DAY_OVERDUE
            , CAST(DAYS_CREDIT_ENDDATE AS NUMERIC) AS DAYS_CREDIT_ENDDATE
            , CAST(DAYS_ENDDATE_FACT AS NUMERIC) AS DAYS_ENDDATE_FACT
            , CAST(AMT_CREDIT_MAX_OVERDUE AS NUMERIC) AS AMT_CREDIT_MAX_OVERDUE
            , CAST(CNT_CREDIT_PROLONG AS NUMERIC) AS CNT_CREDIT_PROLONG
            , CAST(AMT_CREDIT_SUM AS NUMERIC) AS AMT_CREDIT_SUM
            , CAST(AMT_CREDIT_SUM_DEBT AS NUMERIC) AS AMT_CREDIT_SUM_DEBT
            , CAST(AMT_CREDIT_SUM_LIMIT AS NUMERIC) AS AMT_CREDIT_SUM_LIMIT
            , CAST(AMT_CREDIT_SUM_OVERDUE AS NUMERIC) AS AMT_CREDIT_SUM_OVERDUE
            , CREDIT_TYPE
            , CAST(DAYS_CREDIT_UPDATE AS NUMERIC) AS DAYS_CREDIT_UPDATE
            , CAST(AMT_ANNUITY AS NUMERIC) AS AMT_ANNUITY
        from {{ source('raw', 'raw_bureau') }}
    )

select 
*
from bureau