with credit_bureau as (
select
  SK_ID_CURR,
  CAST(sum(case when CREDIT_ACTIVE = 'Active' then 1 else 0 end) as INT64) as N_ACTIVE,
  CAST(sum(case when CREDIT_ACTIVE = 'Sold' then 1 else 0 end) as INT64) as N_SOLD,
  CAST(sum(case when CREDIT_ACTIVE = 'Closed' then 1 else 0 end) as INT64) as N_CLOSED,
  CAST(sum(case when CREDIT_ACTIVE = 'Bad debt' then 1 else 0 end) as INT64) as N_BADD,
  CAST(count(distinct SK_ID_BUREAU) as INT64) as N_DICT_BUREAU_CREDS,
  CAST(max(DAYS_CREDIT) as FLOAT64) as MAX_DAYS_CREDIT,
  CAST(avg(DAYS_CREDIT) as FLOAT64) as AVG_DAYS_CREDIT,
  CAST(max(CREDIT_DAY_OVERDUE) as FLOAT64) as MAX_CREDIT_DAY_OVERDUE,
  CAST(avg(DAYS_CREDIT_ENDDATE) as FLOAT64) as AVG_DAYS_CREDIT_ENDDATE,
  CAST(avg(DAYS_ENDDATE_FACT) as FLOAT64) as AVG_DAYS_ENDDATE_FACT,
  CAST(max(AMT_CREDIT_MAX_OVERDUE) as FLOAT64) as MAX_AMT_CREDIT_MAX_OVERDUE,
  CAST(avg(AMT_CREDIT_MAX_OVERDUE) as FLOAT64) as AVG_AMT_CREDIT_MAX_OVERDUE,
  CAST(sum(AMT_CREDIT_MAX_OVERDUE) as FLOAT64) as SUM_AMT_CREDIT_MAX_OVERDUE,
  CAST(max(CNT_CREDIT_PROLONG) as FLOAT64) as MAX_CNT_CREDIT_PROLONG,
  CAST(avg(AMT_CREDIT_SUM) as FLOAT64) as AVG_AMT_CREDIT_SUM,
  CAST(max(AMT_CREDIT_SUM) as FLOAT64) as MAX_AMT_CREDIT_SUM,
  CAST(sum(AMT_CREDIT_SUM) as FLOAT64) as SUM_AMT_CREDIT_SUM,
  CAST(avg(AMT_CREDIT_SUM_DEBT) as FLOAT64) as AVG_AMT_CREDIT_SUM_DEBT,
  CAST(max(AMT_CREDIT_SUM_DEBT) as FLOAT64) as MAX_AMT_CREDIT_SUM_DEBT,
  CAST(sum(AMT_CREDIT_SUM_DEBT) as FLOAT64) as SUM_AMT_CREDIT_SUM_DEBT,
  CAST(max(AMT_CREDIT_SUM_LIMIT) as FLOAT64) as MAX_AMT_CREDIT_SUM_LIMIT,
  CAST(avg(AMT_CREDIT_SUM_OVERDUE) as FLOAT64) as AVG_AMT_CREDIT_SUM_OVERDUE,
  CAST(max(AMT_CREDIT_SUM_OVERDUE) as FLOAT64) as MAX_AMT_CREDIT_SUM_OVERDUE,
  CAST(sum(AMT_CREDIT_SUM_OVERDUE) as FLOAT64) as SUM_AMT_CREDIT_SUM_OVERDUE,
  CAST(avg(AMT_ANNUITY) as FLOAT64) as AVG_AMT_AMT_ANNUITY,
  CAST(max(AMT_ANNUITY) as FLOAT64) as MAX_AMT_AMT_ANNUITY,
  CAST(sum(AMT_ANNUITY) as FLOAT64) as SUM_AMT_AMT_ANNUITY
from {{ ref('prd_bureau') }}
group by SK_ID_CURR
)
select
*
from credit_bureau